Feature - get issuer
OriginTrail/dkg.js pull request #78
Opened 2023-05-17 16:36 UTC by brkagithub

Added getStateIssuer, getLatestStateIssuer and getAssertionIds, also additional helper functions in blockchain service and validation service. Update was not working correctly on my local node setup for some reason so should test with update before merging, I'll organize this with Nikola before we merge.

2023-05-18 07:33 UTC, u-hubar requested changes
Overall looks good, just some small suggestions how to improve it further

2023-05-18 07:33 UTC, u-hubar commented on managers/asset-operations-manager.js
> +            UAL,
It makes to return state as well imo, just so user has a possibility to check that it's the state he wanted

2023-05-18 07:33 UTC, u-hubar commented on managers/asset-operations-manager.js
>              UAL,
Let's return state here as well

2023-05-18 07:33 UTC, u-hubar commented on managers/asset-operations-manager.js
> +        const assertionIds = await this.blockchainService.getAssertionIds(tokenId, blockchain);
```suggestion
        const states = await this.blockchainService.getAssertionIds(tokenId, blockchain);
```

2023-05-18 07:33 UTC, u-hubar commented on managers/asset-operations-manager.js
> +        let indexOfLastAssertion = assertionIds.length - 1;
```suggestion
        const latestStateIndex = assertionIds.length - 1;
        const latestState = states[latestStateIndex];
```

2023-05-18 07:33 UTC, u-hubar commented on managers/asset-operations-manager.js
>              UAL,
```suggestion
            UAL,
            latestState,
```

2023-05-18 07:33 UTC, u-hubar commented on managers/asset-operations-manager.js
> +        return {
```suggestion
        return {
            UAL,
```

2023-05-18 07:33 UTC, u-hubar commented on managers/asset-operations-manager.js
> +        const assertionId = await this.blockchainService.getAssertionIdByIndex(
```suggestion
        const state = await this.blockchainService.getAssertionIdByIndex(
```

2023-05-18 07:33 UTC, u-hubar commented on managers/asset-operations-manager.js
> +            UAL,
```suggestion
            UAL,
            state,
```

2023-05-18 07:33 UTC, u-hubar commented on managers/asset-operations-manager.js
> +            assertionId,
```suggestion
            state,
```

2023-05-18 07:33 UTC, u-hubar commented on managers/asset-operations-manager.js
> +            assertionIds[indexOfLastAssertion],
```suggestion
            latestState,
```

2023-05-18 07:33 UTC, u-hubar commented on services/validation-service.js
> +    validateAssetGetStateIssuer(UAL, blockchain) {
I guess we should validate stateIndex here as well?

2023-05-18 22:55 UTC, NZT48 approved these changes

2023-05-19 07:18 UTC, djordjekovac approved these changes

2023-05-19 07:46 UTC, merged